"""empty message

Revision ID: 0c544ecf18bb
Revises: b0da02733c22
Create Date: 2022-07-27 03:53:29.073727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c544ecf18bb'
down_revision = 'b0da02733c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'tasklist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'tasklist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
