"""empty message

Revision ID: c73e2db00b81
Revises: 
Create Date: 2022-07-27 03:37:28.363686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73e2db00b81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('tasklist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todos', 'tasklists', ['tasklist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'tasklist_id')
    # ### end Alembic commands ###
